name: Convert Notebooks to PDF

on:
  push:
    branches:
      - main

jobs:
  convert_notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-latex-extra

    - name: Convert all notebooks to PDF
      run: |
        mkdir -p exports
        for notebook in $(find . -name "*.ipynb"); do
          filename=$(basename "$notebook" .ipynb)
          jupyter nbconvert --to pdf --output "exports/${filename}.pdf" "$notebook"
        done

    - name: Commit and push the PDFs
      run: |
        git add exports/*.pdf
        git commit -m "Updated PDF exports"
        git push
